import { get, post } from "./apiService";

const REGISTER_URL = "http://localhost:5000/api/v1/register/createaccount";

const LOGIN_URL = "http://localhost:5000/api/v1/login";

const POST_URL = "http://localhost:5000/api/v1/postapplication"

export function registerUser(userEmail, userPassword) {
  const userDetails = {
    userEmail: userEmail,
    userPassword: userPassword,
    userToken: "",
    isAuthenticated: false,
    step: 1,
    name: "",
    gender: "",
    dateOfBirth: null,
    idNo: "",
    levelOfStudy: "",
    institutionName: "",
    admissionNumber: "",
    institutionBranch: "",
    department: "",
    course: "",
    modeOfStudy: "",
    grade: "",
    courseDuration: "",
    yearOfCompletion: null,
    phoneNumber: "",
    pollingStation: "",
    ward: "",
    location: "",
    subLocation: "",
    physicalAddress: "",
    permanentAddress: "",
    institutionAddress: "",
    institutionPhoneNumber: "",
    amountApplied: "",
    familyStatus: "",
    otherFamilyStatus: "",
    numberOfSiblings: 0,
    estimateFamilyIncome: 0,
    estimateFamilyExpenses: 0,
    livingParent: "",
    fatherName: "",
    fatherAddress: "",
    fatherTelephone: "",
    fatherOccupation: "",
    fatherEmployment: "",
    fatherMainIncomeSource: "",
    motherName: "",
    motherAddress: "",
    motherTelephone: "",
    motherOccupation: "",
    motherEmployment: "",
    motherMainIncomeSource: "",
    guardianName: "",
    guardianAddress: "",
    guardianTelephone: "",
    guardianOccupation: "",
    guardianEmployment: "",
    guardianMainIncomeSource: "",
    siblingsList: [],
    applicationReason: "",
    hasPreviousBursary: "",
    previousBursaryAmount: null,
    previousBursaryDate: null,
    previousFinancialSupport: "",
    previousFinancialSupportDetails: "",
    hasPhysicalImpairment: "",
    physicalImpairmentDetails: "",
    hasChronicIllness: "",
    chronicIllnessDetails: "",
    hasDisabledParent: "",
    disableParentDetails: "",
    hasParentChronicIllness: "",
    parentChronicIllnessDetails: "",
    secondaryMainFundingSource: "",
    collegeMainFundingSource: "",
    universityMainFundingSource: "",
    secondaryOtherFundingSource: "",
    collegeOtherFundingSource: "",
    universityOtherFundingSource: "",
    averageAcademicPerformance: "",
    hasAbsenceRecord: "",
    absenceReason: "",
    absenceDuration: null,
    totalAnnualFees: null,
    lastSemesterBalance: null,
    currentSemesterBalance: null,
    nextSemesterBalance: null,
    helbLoanReceived: null,
    referee1Name: "",
    referee1Address: "",
    referee1PhoneNumber: "",
    referee2Name: "",
    referee2Address: "",
    referee2PhoneNumber: "",
    religiousLeaderName: "",
    religiousLeaderEmail: "",
    religiousLeaderPhone: "",
    religiousLeaderReligionName: "",
    religiousLeaderReligionType: "",
    otherReligionDetials: "",
    chiefName: "",
    chiefEmail: "",
    chiefPhone: "",
    chiefLocation: "",
    chiefSublocation: "",
    fileAttachments: [],
    religiousLeaderApproved: "",
    administratorApproved: "",
    pollingStationApproval: "",
    pollingStationRejectReasons: "",
    cdfCommitteeApproval: "",
    cdfCommitteeRejectReasons: "",
    amountApproved: 0,
  };

  return post(REGISTER_URL, {}, JSON.stringify(userDetails));
}

export function login(userEmail, userPassword) {
  const userDetails = {
    userEmail: userEmail,
    userPassword: userPassword,
    userToken: "",
    isAuthenticated: false,
    step: 1,
    name: "",
    gender: "",
    dateOfBirth: null,
    idNo: "",
    levelOfStudy: "",
    institutionName: "",
    admissionNumber: "",
    institutionBranch: "",
    department: "",
    course: "",
    modeOfStudy: "",
    grade: "",
    courseDuration: "",
    yearOfCompletion: null,
    phoneNumber: "",
    pollingStation: "",
    ward: "",
    location: "",
    subLocation: "",
    physicalAddress: "",
    permanentAddress: "",
    institutionAddress: "",
    institutionPhoneNumber: "",
    amountApplied: "",
    familyStatus: "",
    otherFamilyStatus: "",
    numberOfSiblings: 0,
    estimateFamilyIncome: 0,
    estimateFamilyExpenses: 0,
    livingParent: "",
    fatherName: "",
    fatherAddress: "",
    fatherTelephone: "",
    fatherOccupation: "",
    fatherEmployment: "",
    fatherMainIncomeSource: "",
    motherName: "",
    motherAddress: "",
    motherTelephone: "",
    motherOccupation: "",
    motherEmployment: "",
    motherMainIncomeSource: "",
    guardianName: "",
    guardianAddress: "",
    guardianTelephone: "",
    guardianOccupation: "",
    guardianEmployment: "",
    guardianMainIncomeSource: "",
    siblingsList: [],
    applicationReason: "",
    hasPreviousBursary: "",
    previousBursaryAmount: null,
    previousBursaryDate: null,
    previousFinancialSupport: "",
    previousFinancialSupportDetails: "",
    hasPhysicalImpairment: "",
    physicalImpairmentDetails: "",
    hasChronicIllness: "",
    chronicIllnessDetails: "",
    hasDisabledParent: "",
    disableParentDetails: "",
    hasParentChronicIllness: "",
    parentChronicIllnessDetails: "",
    secondaryMainFundingSource: "",
    collegeMainFundingSource: "",
    universityMainFundingSource: "",
    secondaryOtherFundingSource: "",
    collegeOtherFundingSource: "",
    universityOtherFundingSource: "",
    averageAcademicPerformance: "",
    hasAbsenceRecord: "",
    absenceReason: "",
    absenceDuration: null,
    totalAnnualFees: null,
    lastSemesterBalance: null,
    currentSemesterBalance: null,
    nextSemesterBalance: null,
    helbLoanReceived: null,
    referee1Name: "",
    referee1Address: "",
    referee1PhoneNumber: "",
    referee2Name: "",
    referee2Address: "",
    referee2PhoneNumber: "",
    religiousLeaderName: "",
    religiousLeaderEmail: "",
    religiousLeaderPhone: "",
    religiousLeaderReligionName: "",
    religiousLeaderReligionType: "",
    otherReligionDetials: "",
    chiefName: "",
    chiefEmail: "",
    chiefPhone: "",
    chiefLocation: "",
    chiefSublocation: "",
    fileAttachments: [],
    religiousLeaderApproved: "",
    administratorApproved: "",
    pollingStationApproval: "",
    pollingStationRejectReasons: "",
    cdfCommitteeApproval: "",
    cdfCommitteeRejectReasons: "",
    amountApproved: 0,
  };

  return post(LOGIN_URL, {}, JSON.stringify(userDetails));
}

export function postChanges(applicationDetails) {
    return post(POST_URL, {}, JSON.stringify(applicationDetails));
}
